=begin
#validateapi

#The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveValidateApiClient::LeadEnrichmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LeadEnrichmentApi' do
  before do
    # run before each test
    @instance = CloudmersiveValidateApiClient::LeadEnrichmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LeadEnrichmentApi' do
    it 'should create an instance of LeadEnrichmentApi' do
      expect(@instance).to be_instance_of(CloudmersiveValidateApiClient::LeadEnrichmentApi)
    end
  end

  # unit tests for lead_enrichment_enrich_lead
  # Enrich an input lead with additional fields of data
  # 
  # @param request Input lead with known fields set, and unknown fields left blank (null)
  # @param [Hash] opts the optional parameters
  # @return [LeadEnrichmentResponse]
  describe 'lead_enrichment_enrich_lead test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
