=begin
#validateapi

#The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveValidateApiClient::NameApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NameApi' do
  before do
    # run before each test
    @instance = CloudmersiveValidateApiClient::NameApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NameApi' do
    it 'should create an instance of NameApi' do
      expect(@instance).to be_instance_of(CloudmersiveValidateApiClient::NameApi)
    end
  end

  # unit tests for name_get_gender
  # Get the gender of a first name
  # Determines the gender of a first name (given name)
  # @param input Gender request information
  # @param [Hash] opts the optional parameters
  # @return [GetGenderResponse]
  describe 'name_get_gender test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for name_validate_first_name
  # Validate a first name
  # Determines if a string is a valid first name (given name)
  # @param input Validation request information
  # @param [Hash] opts the optional parameters
  # @return [FirstNameValidationResponse]
  describe 'name_validate_first_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for name_validate_full_name
  # Parse and validate a full name
  # Parses a full name string (e.g. \&quot;Mr. Jon van der Waal Jr.\&quot;) into its component parts (and returns these component parts), and then validates whether it is a valid name string or not
  # @param input Validation request information
  # @param [Hash] opts the optional parameters
  # @return [FullNameValidationResponse]
  describe 'name_validate_full_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for name_validate_last_name
  # Validate a last name
  # Determines if a string is a valid last name (surname)
  # @param input Validation request information
  # @param [Hash] opts the optional parameters
  # @return [LastNameValidationResponse]
  describe 'name_validate_last_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
