=begin
#validateapi

#The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveValidateApiClient::TextInputApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TextInputApi' do
  before do
    # run before each test
    @instance = CloudmersiveValidateApiClient::TextInputApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TextInputApi' do
    it 'should create an instance of TextInputApi' do
      expect(@instance).to be_instance_of(CloudmersiveValidateApiClient::TextInputApi)
    end
  end

  # unit tests for text_input_check_xss
  # Check text input for Cross-Site-Scripting (XSS) attacks
  # Detects XSS (Cross-Site-Scripting) attacks from text input.
  # @param value User-facing text input.
  # @param [Hash] opts the optional parameters
  # @return [XssProtectionResult]
  describe 'text_input_check_xss test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for text_input_check_xss_batch
  # Check and protect multiple text inputs for Cross-Site-Scripting (XSS) attacks in batch
  # Detects XSS (Cross-Site-Scripting) attacks from multiple text input.  Output preverses order of input items.
  # @param value User-facing text input.
  # @param [Hash] opts the optional parameters
  # @return [XssProtectionBatchResponse]
  describe 'text_input_check_xss_batch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for text_input_protect_xss
  # Protect text input from Cross-Site-Scripting (XSS) attacks through normalization
  # Detects and removes XSS (Cross-Site-Scripting) attacks from text input through normalization.  Returns the normalized result, as well as information on whether the original input contained an XSS risk.
  # @param value User-facing text input.
  # @param [Hash] opts the optional parameters
  # @return [XssProtectionResult]
  describe 'text_input_protect_xss test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
