=begin
#validateapi

#The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'cloudmersive-validate-api-client/api_client'
require 'cloudmersive-validate-api-client/api_error'
require 'cloudmersive-validate-api-client/version'
require 'cloudmersive-validate-api-client/configuration'

# Models
require 'cloudmersive-validate-api-client/models/address_get_servers_response'
require 'cloudmersive-validate-api-client/models/address_verify_syntax_only_response'
require 'cloudmersive-validate-api-client/models/check_response'
require 'cloudmersive-validate-api-client/models/first_name_validation_request'
require 'cloudmersive-validate-api-client/models/first_name_validation_response'
require 'cloudmersive-validate-api-client/models/full_email_validation_response'
require 'cloudmersive-validate-api-client/models/full_name_validation_request'
require 'cloudmersive-validate-api-client/models/full_name_validation_response'
require 'cloudmersive-validate-api-client/models/geolocate_response'
require 'cloudmersive-validate-api-client/models/get_gender_request'
require 'cloudmersive-validate-api-client/models/get_gender_response'
require 'cloudmersive-validate-api-client/models/last_name_validation_request'
require 'cloudmersive-validate-api-client/models/last_name_validation_response'
require 'cloudmersive-validate-api-client/models/phone_number_validate_request'
require 'cloudmersive-validate-api-client/models/phone_number_validation_response'
require 'cloudmersive-validate-api-client/models/vat_lookup_request'
require 'cloudmersive-validate-api-client/models/vat_lookup_response'
require 'cloudmersive-validate-api-client/models/whois_response'

# APIs
require 'cloudmersive-validate-api-client/api/domain_api'
require 'cloudmersive-validate-api-client/api/email_api'
require 'cloudmersive-validate-api-client/api/ip_address_api'
require 'cloudmersive-validate-api-client/api/name_api'
require 'cloudmersive-validate-api-client/api/phone_number_api'
require 'cloudmersive-validate-api-client/api/vat_api'

module CloudmersiveValidateApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveValidateApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
